### ISSUE TITLE
Images for the wiki

### ISSUE THREAD

**Issue by Kroffy** [HE-Arc/Persona#1]
<img width="1043" alt="croquis" src="https://user-images.githubusercontent.com/18551560/31130885-e97b7b4e-a858-11e7-8f95-d661f53ec8b6.png">

**Comment by SchnaebeleMarc** [comment]
![wampserverphpversion](https://user-images.githubusercontent.com/26296277/33133787-2bff3232-cf9e-11e7-8096-4f0c26057dac.png)

**Comment by SchnaebeleMarc** [comment]
![wampserverphpversion](https://user-images.githubusercontent.com/26296277/33134004-db4ce716-cf9e-11e7-963b-9ebebded7229.png)

**Comment by SchnaebeleMarc** [comment]
![exemple_env](https://user-images.githubusercontent.com/26296277/33323687-95330c84-d44d-11e7-84a8-6e7fe12cc527.JPG)

**Comment by Staminah** [comment]
![mdl_bdd_persona](https://user-images.githubusercontent.com/18008067/33328789-380fea78-d45b-11e7-97bc-3960f0e214a0.PNG)

**Comment by SchnaebeleMarc** [comment]
![creation_bdd](https://user-images.githubusercontent.com/26296277/33328875-71d724a6-d45b-11e7-970f-70c97784dd74.JPG)

**Comment by greut** [comment]
Utilisant MySQL 5.7.19, je ne comprends pas pourquoi c'est limité à 191.

https://laravel-news.com/laravel-5-4-key-too-long-error

Peut-être la valeur par défaut de Laravel.

**Comment by SchnaebeleMarc** [comment]
![reg_edit_profile](https://user-images.githubusercontent.com/26296277/33344182-553c8250-d488-11e7-8a0d-8ef50748a840.JPG)

**Comment by SchnaebeleMarc** [comment]
![qualities](https://user-images.githubusercontent.com/26296277/33348783-f53c9678-d497-11e7-9f48-1df54d2bf7a3.JPG)
