### ISSUE TITLE
Authentification en HTTPS

### ISSUE THREAD

**Issue by Kroffy** [HE-Arc/Persona#15]
Il existe un problème avec l'authentification de Laravel en HTTPS. Les formulaires redirigent sur une adresse non-sécurisée. Normalement, Laravel devrait "reconnaitre" de lui-même s'il est en HTTP ou en HTTPS, mais ce n'est pas le cas ici.

Du coup on a utilisé un [workaround](https://laracasts.com/discuss/channels/laravel/how-i-can-force-all-my-routes-to-be-https-not-http?page=1) mais il est pas incroyable puisqu'il force les liens en HTTPS...

To be continued.

**Comment by greut** [comment]
`APP_URL` ?

**Comment by Kroffy** [comment]
Changer `http://localhost` en `https://localhost` ne fonctionne pas

**Comment by greut** [comment]
Et https://persona.srvz-webapp.he-arc.ch/ ?

**Comment by Kroffy** [comment]
Non plus :(

**Comment by greut** [comment]
pas de bol :-)

**Comment by Kroffy** [comment]
Fix à la bien qui fonctionne : [fix](https://laracasts.com/discuss/channels/laravel/how-i-can-force-all-my-routes-to-be-https-not-http?page=1).
