### ISSUE TITLE
Regarder les TODOs et les traiter

### ISSUE THREAD

**Issue by Staminah** [HE-Arc/Persona#7]

**Comment by SchnaebeleMarc** [comment]
Le TODO ligne ~185 dans profile-edit.blade.php qui prévoit de déplacer le code JS est fait. J'ai créé une fonction au dessus afin d'éviter les répétitions. Cependant si j'essai de mettre la fonction dans un fichier JS séparé que j’inclus ça ne fonctionne plus.

Edit: Résolu, ça fonctionne même dans un fichier séparé.

**Comment by SchnaebeleMarc** [comment]
Le code ci-dessous dans **profile-common** serait pas plutôt à mettre dans **profile-auth** vu qu'il est disponible que lorsque l'utilisateur est connecté?

```
@if ($user->isMyFriend($user->id) || Auth::user() == $user)
        <li>{{ $user->firstname }} {{ $user->lastname }}</li>
@endif
```

**Comment by SchnaebeleMarc** [comment]
TODO sur les where multiple et les optimisations des tests pour les selected sont fait.

**Comment by Staminah** [comment]
Révisions des TODOs restants. Passage d'une bonne partie d'entre-eux en NOTE, car ils ne sont au final qu'une indication et plus une tâche à réaliser.
